In [15]:
import numpy as np

sales = np.random.normal(
    loc=5000, #loc = mean; provides vals around the mean val
    scale=1000, #scale = std dev; between 4000 to 6000
    size=1000 #generates 1000 vals
)

In [16]:
mean_sales = np.mean(sales)
mean_sales

5069.185053461654

In [17]:
std_sales = np.std(sales)
std_sales

939.3972965678189

In [18]:
p25 = np.percentile(sales, 25)
p25

4439.123420948282

In [19]:
p75 = np.percentile(sales, 75)
p75

5675.258473864646

In [20]:
days_above_avg = np.sum(sales > mean_sales)
days_above_avg

488

In [21]:
hist, bins = np.histogram(sales,bins=10)

print("Histogram Counts:")
print(hist)

print("\nBin Edges:")
print(bins)

Histogram Counts:
[  1   3  22  91 203 284 230 120  41   5]

Bin Edges:
[1209.97629385 1894.59143401 2579.20657417 3263.82171432 3948.43685448
 4633.05199464 5317.6671348  6002.28227495 6686.89741511 7371.51255527
 8056.12769543]

In [ ]:
"or use pandas"

In [25]:
import pandas as pd
df = pd.DataFrame(sales)
df

               0
0    5454.700718
1    5541.572956
2    5574.310448
3    4949.800820
4    5862.470404
..           ...
995  5576.918169
996  4595.879777
997  5896.686537
998  3940.795777
999  3417.679564

[1000 rows x 1 columns]

In [27]:
df.describe()

                 0
count  1000.000000
mean   5069.185053
std     939.867348
min    1209.976294
25%    4439.123421
50%    5029.353921
75%    5675.258474
max    8056.127695